config/routes.rb
Rails.application.routes.draw do

  get 'reservation/Mailer'


  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:index, :show, :edit, :update, :destroy] 
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]  
 end


  resources :listings do
    resources :reservations, except: [:show]
  end

  resources :reservations, only: [:show]

resources :payments, only: [:new, :create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_out" => "clearance/sessions#destroy"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


# if Clearance.configuration.allow_sign_up?
#       get '/sign_up' => 'users#new', as: 'sign_up'
#     end  

   get '/' => 'welcome#index'
   # get '/new_listing' => 'welcome#create_listing'
   # post '/create_listing' => 'listings#create_listing'

  get 'reservation/Mailer'
   get '/about-us' => 'welcome#About_us'
   get '/profile' => 'users#profile'
   get '/boys' => 'boys#boys'
   get '/babes' => 'babes#babes'
   get '/listings/:id/info' => 'listings#info'
   get '/listings/:listing_id/reservations/:id/my_reservation' => 'reservations#my_reservation'
   get '/reservations/:id/braintree/new' => "braintree#new", as: 'braintree_new'
   post '/braintree/:id/checkout' => "braintree#checkout", as: "braintree_checkout"

  get "/reservations/:id/imhost", to:"reservations#host_reservation"

  end 




# if Clearance.configuration.routes_enabled?
#   Rails.application.routes.draw do




  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
#     root 'welcome#index' 

#     resources :passwords,
#       controller: 'passwords',
#       only: [:create, :new]

#     resource :session,
#       controller: 'sessions',
#       only: [:create]

#     resources :users,
#       controller: 'users',
#       only: Clearance.configuration.user_actions do
#         resource :password,
#           controller: 'passwords',
#           only: [:create, :edit, :update]
#       end

#     get '/sign_in' => 'sessions#new', as: 'sign_in'
#     delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

#     if Clearance.configuration.allow_sign_up?
#       get '/sign_up' => 'users#new', as: 'sign_up'
#     end
#   end
# end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController

  	def new
  		@reservation= Reservation.find(params[:id])
  		@client_token = Braintree::ClientToken.generate
  	end
  

def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
  @reservation = Reservation.find(params[:id])
  result = Braintree::Transaction.sale(
   :amount => "10.00", #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
  	ReservationMailer.booking_email(current_user, @reservation.listing.user, @reservation.id).deliver_now
    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
  	p result
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end
end 

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<div align="center" class="demo-frame">

      <%= form_for :checkout_form, url: braintree_checkout_path(@reservation.id), html: { id: "cardForm"} do |form| %>
 
        <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
        <div id="card-number" class="hosted-field""></div>

        <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
        <div id="expiration-date" class="hosted-field"></div>

        <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
        <div id="cvv" class="hosted-field"></div>

        <%= form.hidden_field "payment_method_nonce" %>

        <div class="button-container">
          <%= form.submit "Purchase", disabled: true, class: "button button--small button--green", id: "submit-braintree-btn" %>
        </div>
      <% end %>
    </div>

<script type="text/javascript">
  var form = document.querySelector('#cardForm');
  var submit = document.querySelector("#submit-braintree-btn");
  var authorization = '<%= @client_token %>';

  braintree.client.create({
    // Replace this with your own authorization.
    authorization: authorization
  }, function (clientErr, clientInstance) {
    if (clientErr) {
        console.error(err);
      return;
      // Handle error in client creation
    }

    braintree.hostedFields.create({
      client: clientInstance,
      styles: {
        'input': {
          'font-size': '14pt'
        },
        'input.invalid': {
          'color': 'red'
        },
        'input.valid': {
          'color': 'green'
        }
      },
      fields: {
        number: {
          selector: '#card-number',
          placeholder: '4111 1111 1111 1111'
        },
        cvv: {
          selector: '#cvv',
          placeholder: '123'
        },
        expirationDate: {
          selector: '#expiration-date',
          placeholder: '10/2019'
        }
      }
    }, function (hostedFieldsErr, hostedFieldsInstance) {
      if (hostedFieldsErr) {
        // Handle error in Hosted Fields creation
        return;
      }

      submit.removeAttribute('disabled');

      form.addEventListener('submit', function (event) {
        event.preventDefault();

        hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
          if (tokenizeErr) {
            // Handle error in Hosted Fields tokenization
            return;
          }

          // Put `payload.nonce` into the `payment_method_nonce` input, and then
          // submit the form. Alternatively, you could send the nonce to your server
          // with AJAX.
          document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
          form.submit();
        });
      }, false);
    });
  });

</script>