config/routes.rb
Rails.application.routes.draw do

  get 'reservation/Mailer'


  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:index, :show, :edit, :update, :destroy] 
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]  
 end


  resources :listings do
    resources :reservations, except: [:show]
  end

  resources :reservations, only: [:show]

resources :payments, only: [:new, :create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_out" => "clearance/sessions#destroy"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


# if Clearance.configuration.allow_sign_up?
#       get '/sign_up' => 'users#new', as: 'sign_up'
#     end  

   get '/' => 'welcome#index'
   # get '/new_listing' => 'welcome#create_listing'
   # post '/create_listing' => 'listings#create_listing'

  get 'reservation/Mailer'
   get '/about-us' => 'welcome#About_us'
   get '/profile' => 'users#profile'
   get '/boys' => 'boys#boys'
   get '/babes' => 'babes#babes'
   get '/listings/:id/info' => 'listings#info'
   get '/listings/:listing_id/reservations/:id/my_reservation' => 'reservations#my_reservation'
   get '/reservations/:id/braintree/new' => "braintree#new", as: 'braintree_new'
   post '/braintree/:id/checkout' => "braintree#checkout", as: "braintree_checkout"

  get "/reservations/:id/imhost", to:"reservations#host_reservation"

  end 




# if Clearance.configuration.routes_enabled?
#   Rails.application.routes.draw do




  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
#     root 'welcome#index' 

#     resources :passwords,
#       controller: 'passwords',
#       only: [:create, :new]

#     resource :session,
#       controller: 'sessions',
#       only: [:create]

#     resources :users,
#       controller: 'users',
#       only: Clearance.configuration.user_actions do
#         resource :password,
#           controller: 'passwords',
#           only: [:create, :edit, :update]
#       end

#     get '/sign_in' => 'sessions#new', as: 'sign_in'
#     delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

#     if Clearance.configuration.allow_sign_up?
#       get '/sign_up' => 'users#new', as: 'sign_up'
#     end
#   end
# end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
   has_many :authentications, dependent: :destroy
   has_many :listings
   has_many :reservations

    def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
        name: auth_hash["name"],
        email: auth_hash["extra"]["raw_info"]["email"],
        password: SecureRandom.hex(5)
      )
      user.authentications << authentication
      return user
    end

    # grab fb_token to access Facebook for user data
    def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end
 end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params
    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
  	name = user_params.delete(:name)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
    	user.name = name
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# def new
	# 	@user = user_from_params
	# 	render template: "users/new"
	# end

 #  def create

 #    @user = user_from_params
 #    if @user.save
 #      sign_in @user
 #      redirect_back_or url_after_create
 #    else
 #      render template: "users/new"
 #    end
 #  end


	# private 

	# def user_from_params
	#     email = user_params.delete(:email)
	#     password = user_params.delete(:password)
	#     name = user_params.delete(:name)

	#     Clearance.configuration.user_model.new(user_params).tap do |user|
	#       user.email = email
	#       user.password = password
	#       user.name =  name 
	#     end
	#   end
	#   # params.require(:user).permit(:name, :email, :password)


end

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

   <% if signed_in? %>
  <%= current_user.email %>
  <%= button_to "Sign out", sign_out_path, method: :delete %>
<% else %>
<% end %>
  <%= link_to "Sign in", sign_in_path %>

  <%= form_for @user do |form| %>
  
   <div class="text-field">
     <%= form.label :email %>
   <%= form.text_field :email, type: 'email' %>
 </div>

 <div>
    <%= form.label :name %> 
    <%= form.text_field :name, type:'text' %> 
 </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
</div>


    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/profile.html.erb
	<h2 align="center"> Welcome <%= current_user.name %> to Pairbnb</h2>


<form align="right" class="list_button" method="get" action="/listings/new">
    <button type="submit">List</button>
</form>
<br>
<form align="right" class="my_reservation_button" method="get" action= "/listings/:listing_id/reservations/:id/my_reservation">
    <button type="submit">My Reservation</button>
</form>

  <div class="page-header">
        <h2>Here's Your Listing</h2>

    </div>
    <br>
   <% if current_user.listings.empty? %>
  <h4>You have not posted any listings. Earn some extra dollar by listing yourself <a href="/listings/new">Here!</a></h4>
<% else %>
<% current_user.listings.each do |profile| %>
    <div class="row active-with-click">
        <div class="col-md-4 col-sm-6 col-xs-12">
            <article class="material-card Red">
                <h2>
                    <%= current_user.name%>
                    <strong>
                        <i class="fa fa-fw fa-star"></i> 
                        <%= profile.rate %> , <%=profile.today_age %>
                    </strong>
                   <form align="right" class="edit_button" method="get" action="/listings/<%= profile.id %>/edit">
                     <button type="submit">Edit</button>
                 </form>
                </h2>
                <div class="mc-content">
                    <div class="img-container">
                        <div class="image-div container">

                      <% if profile.photos?%>
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                          <!-- Indicators -->
                          <ol class="carousel-indicators">
                            <%for i in 0..profile.photos.count - 1 %>
                              <li data-target="#myCarousel" data-slide-to="<%=i%>"></li>
                              <%end%>
                          </ol>

                          <!-- Wrapper for slides -->
                          <div class="carousel-inner" role="listbox">
                            <% profile.photos.each_with_index do |photo, index|%>
                              <div class="item <%= 'active' if index == 0%>">
                                <%= image_tag (photo.large.url) %>
                              </div>
                              <%end%>
                          </div>
                          <!-- Left and right controls -->
                          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>

                          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>
                     <%end%>
                    </div>
                       <!--  <img class="img-responsive" src="http://u.lorenzoferrara.net/marlenesco/material-card/thumb-christopher-walken.jpg"> -->
                    </div>
                </div>
                   <div class="mc-description">
                        <%= profile.description %>
                    </div>
                <a class="mc-btn-action">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="mc-footer">
          
                    <a class="fa fa-fw fa-facebook"></a>
                    <a class="fa fa-fw fa-twitter"></a>
                    <a class="fa fa-fw fa-linkedin"></a>
                    <a class="fa fa-fw fa-google-plus"></a>
                </div>
            </article>
        </div>
        <% end %>
        <% end %>




<br></br>