config/routes.rb
Rails.application.routes.draw do

  get 'reservation/Mailer'


  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, only: [:index, :show, :edit, :update, :destroy] 
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]  
 end


  resources :listings do
    resources :reservations, except: [:show]
  end

  resources :reservations, only: [:show]

resources :payments, only: [:new, :create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_out" => "clearance/sessions#destroy"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root 'welcome#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


# if Clearance.configuration.allow_sign_up?
#       get '/sign_up' => 'users#new', as: 'sign_up'
#     end  

   get '/' => 'welcome#index'
   # get '/new_listing' => 'welcome#create_listing'
   # post '/create_listing' => 'listings#create_listing'

  get 'reservation/Mailer'
   get '/about-us' => 'welcome#About_us'
   get '/profile' => 'users#profile'
   get '/boys' => 'boys#boys'
   get '/babes' => 'babes#babes'
   get '/listings/:id/info' => 'listings#info'
   get '/listings/:listing_id/reservations/:id/my_reservation' => 'reservations#my_reservation'
   get '/reservations/:id/braintree/new' => "braintree#new", as: 'braintree_new'
   post '/braintree/:id/checkout' => "braintree#checkout", as: "braintree_checkout"

  get "/reservations/:id/imhost", to:"reservations#host_reservation"

  end 




# if Clearance.configuration.routes_enabled?
#   Rails.application.routes.draw do




  # resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]

  # resources :users, controller: "clearance/users", only: [:create] do
  #   resource :password,
  #     controller: "clearance/passwords",
  #     only: [:create, :edit, :update]
  # end

  # get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  # delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"
#     root 'welcome#index' 

#     resources :passwords,
#       controller: 'passwords',
#       only: [:create, :new]

#     resource :session,
#       controller: 'sessions',
#       only: [:create]

#     resources :users,
#       controller: 'users',
#       only: Clearance.configuration.user_actions do
#         resource :password,
#           controller: 'passwords',
#           only: [:create, :edit, :update]
#       end

#     get '/sign_in' => 'sessions#new', as: 'sign_in'
#     delete '/sign_out' => 'sessions#destroy', as: 'sign_out'

#     if Clearance.configuration.allow_sign_up?
#       get '/sign_up' => 'users#new', as: 'sign_up'
#     end
#   end
# end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :listing
	belongs_to :user
	validate :check_overlapping_dates


	def check_overlapping_dates
		listing.reservations.each do |old_booking|
			if overlap?(self , old_booking)
				return errors.add(:overlapping_dates, "The booking dates are conflict with existing reservation. Try another date.")
			end 
		end 
	end 

	def overlap?(x,y)
		(x.start_date_and_time - y.end_date_and_time) * (y.start_date_and_time - x.end_date_and_time) > 0
	end 

def num_of_hours
	(end_date_and_time - start_date_and_time) / 3600
end 

def price_per_hours 
	listing.rate
end 

def total_price
	( listing.rate * num_of_hours)
end 

def name_of_user
	listing.user.name
end 
	# def reserved_dates
	# 	(self.start_date_and_time..self.end_date_and_time).to_a
	# end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def new
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.new

	end

	def reservation_params
      params.require(:reservation).permit(:user_id, :listing_id, :start_date_and_time, :end_date_and_time, :comments)
    end

	def create
		@listing = Listing.find(params[:reservation][:listing_id])
		@reservation = current_user.reservations.new(reservation_params)
		@reservation.listing = @listing # setting the listing_id col take value from this objexct @listing
		if @reservation.save
		#Tell the ReservationMailer to send a welcome email after save
		render template: "reservations/show"
		else 
		flash[:notice]="booking unsuccessful: check that dates are not already booked?"
		render :new	
		end
	end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		render template:"reservations/deleted"
	end
	def show
		@reservation = Reservation.find(params[:id])
	end

	def my_reservation
		@reservation = current_user.reservations
	 
	end

	def host_reservation
		# @listings = current_user.listings #all my posted listings
		@reservation = Reservation.find(params[:id])
		render :host_reservation
		# @reservation = Reservation.find(params[:reservation][:listing_id])
		# @user = User.find(params[:reservation_id][:listing_id])
	end 


end 

app/views/reservations/deleted.html.erb
<h2> You've successfully deleted <h2>

app/views/reservations/host_reservation.html.erb
	Somebody booked this: 
	<p>Description<%= @reservation.listing.description %></p>
	<p>This fella <%= @reservation.user.name%>booked this above.</p>

app/views/reservations/my_reservation.html.erb
<br>
<br>
<table>

	<tr>
		<th> Number </th>
		<th> Name <th>
		<th> Start Date and Time </th>
		<th> End Date and Time</th>
		<th> Comments</th>
		<th> Price Per Hour</th>
		<th> Number of Hours Reserved</th>
		<th> Total price </th>
		<th> Action </th>
	</tr>

	<% @reservation.each_with_index do|reservation, number| %>
		<tr> 	
			<td> <%= number + 1 %>
			<td> <a href="/listings/<%= reservation.listing_id %>/info"> <%= reservation.name_of_user %></a> </td> 
			<td> <%= reservation.start_date_and_time %></td>
			<td> <%= reservation.end_date_and_time %></td>
			<td> <%= reservation.comments%>	</td>
			<td> <%= reservation.price_per_hours%></td>
			<td> <%= reservation.num_of_hours%></td>
			<td> <%= reservation.total_price %></td>
			<td><%= link_to "Cancel Reservation", listing_reservation_path(reservation.listing,reservation), method: :delete , data: { confirm: 'Sure ah?'}  %></td>
		</tr>
<% end %>
</table>

app/views/reservations/new.html.erb
<h2> Make Reservation </h2>
<br>

<%= form_for [@listing,@reservation] do |form| %>
 <%= form.hidden_field :user_id, :value => current_user.id %>
  <%=form.hidden_field :listing_id, :value => @listing.id  %>
  <h4>Start date:</h4><%= form.datetime_field :start_date_and_time %><br>
  <br>
  <h4>End date:</h4><%= form.datetime_field :end_date_and_time %><br>
  <br>
  <h4>Comments:</h4><%= form.text_field :comments %>
  <br>

<br><%= form.submit %></br>
<% end %>

app/views/reservations/show.html.erb
<h2> You've successfully booked <h2>
<br>
<%= link_to "Make Payment", braintree_new_path(@reservation.id) %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h2> Click <a href="/listings/:listing_id/reservations/:id/my_reservation?"> here </a> to view all your reservation </h2>